import React from 'react';

export default function HeroSection({ kpData, aiSummary, isSummarizing, onOpenModal }) {
  // Get latest Kp
  const latestKpData = kpData && kpData.length > 0 ? kpData[kpData.length - 1] : null;
  const kpString = latestKpData ? latestKpData.Kp : null;
  const kp = kpString !== null && !isNaN(parseFloat(kpString)) ? parseFloat(kpString) : null;

  let statusClass = "border-slate-800 shadow-none";
  let textColor = "text-slate-400";
  let label = "SIGNAL LOSS";

  if (kp !== null) {
    if (kp <= 4) {
      statusClass = "border-alert-green shadow-[0_0_20px_rgba(16,185,129,0.3)]";
      textColor = "text-alert-green";
      label = "QUIET / UNSETTLED";
    } else if (kp <= 6) {
      statusClass = "border-alert-yellow shadow-[0_0_30px_rgba(245,158,11,0.6)] animate-pulse-slow";
      textColor = "text-alert-yellow";
      label = "G1-G2 STORM";
    } else {
      statusClass = "border-alert-red shadow-[0_0_40px_rgba(239,68,68,0.8)] animate-pulse-fast";
      textColor = "text-alert-red";
      label = "G3-G5 STORM";
    }
  }

  // Calculate rotation for gauge (-90deg to 90deg)
  const rotation = kp !== null ? -90 + (kp / 9) * 180 : -90;

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-stretch">
      
      {/* Left Column: Planetary K-Index (Kp) */}
      <div 
        className={`glass-panel cursor-pointer hover:bg-white/10 ${statusClass} flex flex-col items-center justify-center p-8`}
        onClick={() => onOpenModal && onOpenModal({ type: 'kp_info' })}
      >
        <div className="text-center mb-6">
          <h2 className="text-xl text-slate-300 font-bold tracking-widest">PLANETARY K-INDEX (Kp)</h2>
          <p className={`text-sm mt-2 ${textColor} tracking-widest`}>{label}</p>
        </div>

        <div className="relative w-64 h-32 overflow-hidden flex justify-center mt-4">
          {/* Gauge Background */}
          <div className="w-64 h-64 border-8 border-slate-700 rounded-full absolute top-0" />
          
          {/* Needle */}
          <div 
            className="absolute bottom-0 w-1 h-32 bg-slate-400 origin-bottom transition-transform duration-1000 ease-out z-10"
            style={{ transform: `rotate(${rotation}deg)` }}
          >
            <div className="w-3 h-3 bg-white rounded-full absolute -top-1.5 -left-1 shadow-[0_0_10px_white]" />
          </div>

          {/* Center dot */}
          <div className="absolute bottom-[-8px] w-4 h-4 bg-slate-300 rounded-full z-20" />
        </div>

        <div className="text-5xl font-bold mt-4 font-mono text-white">
          {kp !== null ? kp.toFixed(2) : '--'}
        </div>
      </div>

      {/* Right Column: AI Summary */}
      <div className="glass-panel flex flex-col p-8 border-l-4 border-l-aviation-orange">
        <h2 className="text-sm text-slate-400 font-bold tracking-widest mb-4">SYSTEM STATUS BRIEF // GENERATED BY HELIOS-AI</h2>
        
        <div className="flex-1 flex flex-col justify-center text-slate-200 leading-relaxed font-mono text-sm">
          {isSummarizing ? (
            <div className="text-aviation-orange animate-pulse-fast">
              [ SCANNING TELEMETRY... ]
            </div>
          ) : (
            <div dangerouslySetInnerHTML={{ __html: aiSummary ? aiSummary.replace(/\*\*(.*?)\*\*/g, '<strong class="text-white">$1</strong>') : 'WAITING FOR TELEMETRY...' }} />
          )}
        </div>
      </div>
    </div>
  );
}
